# Numpy

In [2]:
class classabc:
    def __init__(self,num):
        self.num=num
        
ob1=classabc(1)

In [3]:
#1D array
import numpy as np
a=np.array([1,2,3,'b'])
print(a)

['1' '2' '3' 'b']


In [4]:
#2D array
import numpy as np
b=np.array([[1,2],[3,4],[5,6]])
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [5]:
#minimum dimension
import numpy as np
b=np.array([1,2,3,4,5], ndmin=2)
print(b)

[[1 2 3 4 5]]


In [6]:
#parse parameter
import numpy as np
b=np.array([1,2,3,4,5], dtype=complex)
print(b)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


In [9]:
'''

numpy.dtype(object, align, copy)

object :

align :

copy : Make new copy of data object

'''

'\n\nnumpy.dtype(object, align, copy)\n\nobject :\n\nalign :\n\ncopy : Make new copy of data object\n\n'

In [10]:
#Slicing
a=[1,2,3,4,5,6,7,8,9,10,11,12]
s=slice(2,7,2)
print(a[s])
print(a[2:7:2])

[3, 5, 7]
[3, 5, 7]


In [11]:
#Write a program to Splice a single value from a certain array

import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
print(a[2:3])

[3]


In [12]:
x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,0,1],[0,1,0]]
print(y)

[1 2 3]


In [13]:
#Illustrate integer indexing in an array of 5X3 
x = np.array([[1, 2,3], [4,5,6], [6,7,8],[9,10,11],[12,13,14]])
y= x[[1,2,1,0],[1,2,0,0]]
print(y)

[5 8 4 1]


In [14]:
a=np.arange(0,60,5)
a= a.reshape(3,4)

print(a)

print('Modified array is: ')
for x in np.nditer(a):
    print(x),

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
Modified array is: 
0
5
10
15
20
25
30
35
40
45
50
55


In [15]:
import numpy as np
a = np.arange(0,80,5)
a = a.reshape(4,4)
print ('Original array is:')
print (a)
print ('\n')

print ('Transpose of the original array is:')
b = a.T
print (b)
print('\n') 

print ('Sorted in C order:')
c = b.copy(order = 'C')
print (c)
for x in np.nditer(c):
   print (x),

print ('\n')

print ('Sorted in F-order:')
c = b.copy(order = 'F')
print (c)
for x in np.nditer(c):
   print (x),

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]
 [60 65 70 75]]


Transpose of the original array is:
[[ 0 20 40 60]
 [ 5 25 45 65]
 [10 30 50 70]
 [15 35 55 75]]


Sorted in C order:
[[ 0 20 40 60]
 [ 5 25 45 65]
 [10 30 50 70]
 [15 35 55 75]]
0
20
40
60
5
25
45
65
10
30
50
70
15
35
55
75


Sorted in F-order:
[[ 0 20 40 60]
 [ 5 25 45 65]
 [10 30 50 70]
 [15 35 55 75]]
0
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75


In [16]:
#WAP TO FIND ROUND OFF VALUES OF DECIMAL POINTS
a=np.array([1.34,2.45,2.222,7,45])
print(a,1)
np.around(a)

[ 1.34   2.45   2.222  7.    45.   ] 1


array([ 1.,  2.,  2.,  7., 45.])

In [17]:
#WAP TO DEMOSNTRATE BASIC ARITHMATIC OPERATIONS ON ARRAY
a=np.arange(0,10,2)
print(a)

print("\nAddition:\n")
b=a+2
print(b)

print("\nSubstraction:\n")
c=a-2
print(c)

print("\nMultiplication:\n")
d=a*2
print(d)

print("\nDivision:\n")
d=a/2
print(d)


[0 2 4 6 8]

Addition:

[ 2  4  6  8 10]

Substraction:

[-2  0  2  4  6]

Multiplication:

[ 0  4  8 12 16]

Division:

[0. 1. 2. 3. 4.]


In [18]:
#TAKE AN ARRAY WITH ATLEAT 7 INTEGET VALUES AND CALCULATE THEIR RECIPROCAL
a=np.arange(1,10)
print(a)

b=1/a
print(b)

[1 2 3 4 5 6 7 8 9]
[1.         0.5        0.33333333 0.25       0.2        0.16666667
 0.14285714 0.125      0.11111111]


In [19]:
#FIND THE NTH POWER OF VALUES OF AN ARRAY(Size min 4)
a=np.arange(0,5)
print(a)
u_in=int(input("INput the power: "))
b=pow(a,u_in)
print(b)

[0 1 2 3 4]
INput the power: 5
[   0    1   32  243 1024]


In [20]:
#WAP TO FIND THE PERCENTILE OF ARRAY ELEMENTS
a=np.arange(0,5)
print(np.percentile(a,50))

2.0


In [21]:
#WAP TO FIND THE AVERAGE, MODE, STANDARD DEVIATION , VARIANCE OF ARRAY ELEMENT
from scipy import stats

a=np.arange(1,10)
print(np.mean(a))
print(np.std(a))
print(np.var(a))

b=[1,2,3,3,3,3,3]
print(stats.mode(b)[0][0])

5.0
2.581988897471611
6.666666666666667
3


In [22]:
#IMPLEMRNT ANY ONE SORT USING NUMPY
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr)) 



[0 1 2 3]
