# CHANDAN KUMAR SINGH

# 1828236

In [15]:
#WAP to find degree of a polynomial  equation.

import numpy as np

num = [1,2,3,4]

poly = np.poly1d(num)

print(poly)


deg = poly.order

print(deg)

   3     2
1 x + 2 x + 3 x + 4
3


In [2]:
#WAP to find factorial of a number.
import numpy as np

n = int(input("Enter the number "))

fact = np.math.factorial(n)

print(fact)

Enter the number 5
120


In [3]:
#WAP to find roots of a Quadratic Equation

from math import sqrt


coeff = [1,2,3]

poly = np.poly1d(coeff)

print(poly)

roots = np.roots(coeff)

print(roots)

   2
1 x + 2 x + 3
[-1.+1.41421356j -1.-1.41421356j]


In [17]:
#WAP to print diagonal elements of a matrix.

 
mat = np.matrix('[1, 2, 3; 4, 5, 6; 7, 8, 9]') 
         

diag = mat.diagonal() 
   
print(diag)


[[1 5 9]]


In [12]:
#WAP to find profit or loss for a given CP and SP.

actual_cost = float(input(" Actual Product Price: "))
sale_amount = float(input(" Sales Amount: "))
 
if(actual_cost > sale_amount):
    amount = actual_cost - sale_amount
    print("Total Loss Amount = {0}".format(amount))
elif(sale_amount > actual_cost):
    amount = sale_amount - actual_cost
    print("Total Profit = {0}".format(amount))
else:
    print("No Profit No Loss!!!")

 Actual Product Price: 10000
 Sales Amount: 12000
Total Profit = 2000.0


In [16]:
#WAP to sort the matrix row wise and Column wise.



a = np.array([[1,4], [3,1]])
a.sort(axis=1)

print(a)

a.sort(axis=0)

print(a)

[[1 4]
 [1 3]]
[[1 3]
 [1 4]]
